### ISSUE TITLE
Match Halide execution to floating point IPs

### ISSUE THREAD

**Issue by Kuree** [StanfordAHA/lassen#109]
The `bfloat` implementation in Halide seems to be consistent with the IP with `rnd=1`. It would much easier if we can use that mode instead.

**Comment by mahorowitz** [comment]
I think we should check which path is doing what type of rounding, and not just make the hardware match our Halide implementation.  I thought the hardware was doing round to nearest even, which is what I think we want.  If Halide is just doing round to nearest, we probably should change Halide, and not the hardware.  But I could be completely wrong on what is implemented on either side

**Comment by Kuree** [comment]
IEEE defines 5 different valid rounding rules:https://en.wikipedia.org/wiki/IEEE_754#Rounding_rules
I believe any of them are IEEE compliant implementation.

We will see if we can change Halide's behavior tomorrow.

**Comment by rdaly525** [comment]
<img width="651" alt="Screen Shot 2019-06-04 at 3 50 34 PM" src="https://user-images.githubusercontent.com/14632648/58918794-9f01c380-86e0-11e9-9a1f-57712730b694.png">

Here are the rounding modes for the IP

**Comment by rdaly525** [comment]
I am surprised that Halide does not use round to nearest even.

@jeffsetter, can you investigate exactly what rounding mode is being used by halide?

**Comment by Kuree** [comment]
@rdaly525 We're implementing rnd=0 mode in Halide right now.

**Comment by rdaly525** [comment]
So, just to be clear: Halide's implementation is RNE and RTL's implementation is RNE, but we are getting different results?

**Comment by Kuree** [comment]
Halide is using rnd=1 and we're using rnd=0 in RTL. We will change the Halide implementation to match with the RTL.
