### ISSUE TITLE
Lassen Bug Tracker

### ISSUE THREAD

**Issue by rdaly525** [StanfordAHA/lassen#123]
FP_Mult Error mode issue
-Problem: RTL mismatched FPVector and Halide due to wrapper
-Solution: Use DW FP IP instead
-Verification: Lassen RTL tests
-Can be resolved today

SLT/SGT Bug
-problem: SMT cannot infer SLT and SGT. But the random tests are passing
-Solution: Still debugging (Caleb)
-Verification: Automapper finding SLT and SGT

SubExp Bug
-problem: A small portion of random tests (~5%) are failing the SubExp micro op RTL
-solution: Still debugging (Lenny/anyone else wants to help?)
-verification: Lassen RTL tests

**Comment by leonardt** [comment]
RE: SubExp Bug

Can you point to an example failure? It would be useful to get the specific inputs causing the failure so we can debug it. Is this on master?

**Comment by rdaly525** [comment]
actions = [Poke(WrappedPE.inst, 42081637117181558932), Poke(WrappedPE.CLK, 0), Poke(WrappedPE.data0, 22666), Poke(WrappedPE.data1, 31920), Eval(), Expect(O0, 7050)]

Got      : 0x3ddf
Expected : 0xbddf
i        : 5
Port     : WrappedPE.O0

**Comment by leonardt** [comment]
RE: SubExp Bug we believe this was because an old version of fault was not generating the sigend values properly, we will assume it's fixed unless it pops again either locally for someone or on buildkite/travis

**Comment by rdaly525** [comment]
SLT/SGT bug is due to hwtypes issue here: https://github.com/leonardt/hwtypes/pull/52

**Comment by leonardt** [comment]
I believe these have all been resolved, please re open if that's not the case

**Comment by cdonovick** [comment]
leonardt/hwtypes#52 was never merged

**Comment by leonardt** [comment]
merged

**Comment by leonardt** [comment]
(release in process) https://travis-ci.org/leonardt/hwtypes/builds/546921411
