### ISSUE TITLE
More Complex Ops

### ISSUE THREAD

**Issue by rdaly525** [StanfordAHA/lassen#139]
We need Round, Floor and Ceil. If we have one of these ops, the other two are very easy to create by just adding or subtracting 0.5 appropriately.

@nikhilbhagdikar, could you add these to our complex ops (in lassen/stdlib/) and add some tests?

For the tests, please use hwtypes.FPVector in order to construct and manipulate python floating point values

**Comment by steveri** [comment]
@rdaly525 @nikhilbhagdikar Is this not the same as https://github.com/StanfordAHA/lassen/issues/29 ?

**Comment by rdaly525** [comment]
You are correct
