### ISSUE TITLE
Warnings need to be fixed

### ISSUE THREAD

**Issue by rdaly525** [StanfordAHA/lassen#149]
The #148 PR is passing with the exception of travis killing it due to the log being too long.

If you download the raw log here, you can see that message at the bottom.
https://travis-ci.com/StanfordAHA/lassen/builds/129343573 

The log is too long due to there being warnings in the code. These warnings are coming from peak.auto_assembler

**Comment by leonardt** [comment]
This should help https://github.com/StanfordAHA/lassen/pull/150

Depends on a peak branch https://github.com/cdonovick/peak/tree/move-assembler-utils

Waiting for the travis build

**Comment by leonardt** [comment]
It looks like metamapper is still triggering a warning

```
metamapper/metamapper/peakmapper.py:6: DeprecationWarning: auto_assembler.py is deprecated please move to assembler
```

I'm debugging the buildkite build, it looks to be an environment issue.

**Comment by rdaly525** [comment]
I have a branch on Metamapper called "warnings" that fixes these issues. Trying to fix the travis on that repo before I merge though.

**Comment by leonardt** [comment]
Okay tests seem to be proceeding along in buildkite https://buildkite.com/stanford-aha/lassen/builds/333#b73aa5bb-7a8b-4ede-bf1a-828105b9b4ca, with the metamapper warning branch this build should be back to green soon

**Comment by rdaly525** [comment]
Closing
