### ISSUE TITLE
Flags are wrong for FPAdd

### ISSUE THREAD

**Issue by rdaly525** [StanfordAHA/lassen#27]
We need to the flags to be correct in order to do all the floating point comparison operations. (<,<=,==,!=,etc...)

Ideally this can be done just using the already existent flags and that the cond.py does not actually depend on the instruction.

**Comment by rdaly525** [comment]
The flags can be implemented using https://community.arm.com/developer/ip-products/processors/b/processors-ip-blog/posts/condition-codes-4-floating-point-comparisons-using-vfp

**Comment by nikhilbhagdikar** [comment]
FP flags have been fixed and a separate cond section will be implemented for floating point ops by Ross/Caleb based on Monday's discussion.

**Comment by rdaly525** [comment]
This has been resolved by #99
