### ISSUE TITLE
Better support for FPSub

### ISSUE THREAD

**Issue by rdaly525** [StanfordAHA/lassen#28]
I propose there be a dedicated configuration bit that will can flip the sign bit of floating point values. This would prevent burning an additional PE when doing FPSUB. (You can flip the sign bit by first doing an XOR in a separate PE).

@alexcarsello, thoughts?

**Comment by nikhilbhagdikar** [comment]
Ross has implemented a better fpsub in lassen which shares the underlying FP Add hardware.

**Comment by steveri** [comment]
@rdaly525 looks like this has been resolved? should we close the issue?
