### ISSUE TITLE
Add support for casting int to float

### ISSUE THREAD

**Issue by rdaly525** [StanfordAHA/lassen#32]

**Comment by nikhilbhagdikar** [comment]
This is done and was explained during previous meeting.

**Comment by steveri** [comment]
@rdaly525 nikhil says this is done...should we close this issue?

**Comment by phanrahan** [comment]
Do we have a comprehensive set of unit tests?

**Comment by steveri** [comment]
> Do we have a comprehensive set of unit tests?
I guess this is a question for @nikhilbhagdikar and/or @Kuree ?

**Comment by rdaly525** [comment]
This is done in test_micro.py in the following tests:

test_sint_to_float
test_uint_to_float
