### ISSUE TITLE
Why is irq listed as PE output

### ISSUE THREAD

**Issue by Kuree** [StanfordAHA/lassen#39]
It seems like `irq` signal gets propagates into `canal` as a valid output. As a result, the `irq` signal goes to all the switchbox muxes, potentially increasing the area. What is this signal doing? Based on the code here:
https://github.com/StanfordAHA/lassen/blob/59095149bd7ce4f8e61e6e56f54ccd866a74d67c/lassen/sim.py#L257-L261
is `irq` a way to output constant 0 to the application network? If not, can someone explain to me which applications we have so far need it? Is it a form of premature optimization?

**Comment by rdaly525** [comment]
it looks like @priyanka-raina or @phanrahan added this. I am not aware of any plan to have an interrupt request. I think it can be safely removed. Pat and/or Priyanka, can you confirm this was not an intended feature?

**Comment by rdaly525** [comment]
PR in #40

**Comment by leonardt** [comment]
IRQ was used in the old PE (jade) as a debug/breakpoint trigger. See https://docs.google.com/document/d/1OXBBVk1exV1Fa65yBVIGxb6pd33UTEOqxWl0fBEhGRU/edit?usp=sharing for some more info on the old version of the PE spec. There was a configuration field for `debug_trig` and `debug_trig_p` which set the values to be watched and an `irq_en` field in the `op_code`.

I'm not aware of the plans for garnet w.r.t. `irq` (e.g. if it is meant to be dropped, included, or changed)

**Comment by Kuree** [comment]
Assuming we're following the old PE spec and add `irq` in the `op_code`, the signal itself should not go to the routing fabric. Given the fact that it's never used during testing, I'm leaning towards to drop it.

**Comment by rdaly525** [comment]
Started irq branch called 'irq'

**Comment by rdaly525** [comment]
IRQ is removed
