### ISSUE TITLE
Broken lassen master branch

### ISSUE THREAD

**Issue by Kuree** [StanfordAHA/lassen#43]
See here: https://travis-ci.com/StanfordAHA/GarnetFlow/builds/110987402
and here: https://travis-ci.com/StanfordAHA/lassen/builds/110816257

In the future people should run the garnet flow to make sure that nothing is broken...

**Comment by rdaly525** [comment]
I will fix.

**Comment by Kuree** [comment]
Thanks.

**Comment by rdaly525** [comment]
Fix in #44. Should fix Garnet as well.
