### ISSUE TITLE
DELAY mode doesn't work in RTL

### ISSUE THREAD

**Issue by Kuree** [StanfordAHA/lassen#49]
![Screenshot from 2019-05-10 11-44-41](https://user-images.githubusercontent.com/6099149/57549962-c780e280-7319-11e9-80ae-8c49efbbaf56.png)

Here we have a PE configured as `mult (1, reg)`, where `data0` is configured as a const register, and `data1` is configured as `DEALY`.
0: Single from `data0` connection box. Since `data0` is in `CONST` mode, as indicated in signal 2, this is expected
1: Signal from `data1` connection box. This is the input the the PE core.
2. Register mode for `data0`. 0 is `CONST` so this is expected.
3. Register const value for `data0`, this is expected since it's multiply by 1.
4. Register mode for `data1`. 11 is 3, which is `DELAY` mode. This is also correct.
5. This is the signal going to the ALU unit. Notice that there is no delay!
6. This is the output from the ALU unit. No delay either.

Mode flags are here:
https://github.com/StanfordAHA/lassen/blob/5ed30d62436fbde91c70ee7bedcaba1dfb445c49/lassen/mode.py#L9-L17

**Comment by leonardt** [comment]
The issue was that in the test bench was setting the input values, then raising the clock causing a posedge which propagates the input values immediately. Changing the test bench to set the inputs while the clock was high, then stepping the clock a full cycle exhibited the correct behavior.
