### ISSUE TITLE
add w/ external carry feature dropped?

### ISSUE THREAD

**Issue by leonardt** [StanfordAHA/lassen#54]
Right now the carry in for the normal add op is always set to 0 (see https://github.com/StanfordAHA/lassen/blob/master/lassen/sim.py#L60).  IIRC `jade` set the `cin` using a one-bit input (see https://github.com/StanfordAHA/CGRAGenerator/blob/master/hardware/generator_z/pe_new/pe/rtl/test_pe_comp.svp#L507) which enables the construction of a carry chain adder (e.g. for a 32 bit add).

Did we intend to drop this feature?

**Comment by rdaly525** [comment]
I think we should add it back in. Ill do a PR

**Comment by rdaly525** [comment]
Fixed by #86
