### ISSUE TITLE
List of possibly missing ops we would like to be able to support in lassen

### ISSUE THREAD

**Issue by rdaly525** [StanfordAHA/lassen#61]
- 32-bit Add
- 32-bit Mul
- Carry-in
- Counter mode
- qualified register (valid)
- Breakpoints/Watchpoints/IRQ

**Comment by phanrahan** [comment]
Another question. Diablo had support for counters, which is not in Lassen. Do we need additional support for counters?

**Comment by rdaly525** [comment]
It would be great if we could support them. There are a lot of counters in jeff's applications. I do not think these were tested much (if at all) in Diablo.

**Comment by rdaly525** [comment]
We have support for 32-bit Add (carry-in), but we are not supporting Breakpoints/IRQ, counter mode, and a dynamically enabled register. 

There are workarounds for qualfiied register by using another PE to for the enable Mux.
Workarounds for 32-bit mul is that we can use more PE tiles
Workaround for counter mode is to just use multiple PE tiles
