### ISSUE TITLE
signed ops is not working in RTL

### ISSUE THREAD

**Issue by Kuree** [StanfordAHA/lassen#70]
Probably the same issue with `asr`. 

I haven't test `smin` yet, but I'm suspecting it's the same error. 

See `smax` branch.

See: https://travis-ci.com/StanfordAHA/lassen/builds/111969902

**Comment by Kuree** [comment]
List of additional ops that doesn't work:
1. slt
2. sle
3. smax
4. smin

**Comment by leonardt** [comment]
I suspect this is a similar issue to asr w.r.t. to polymorphism

**Comment by leonardt** [comment]
Fixed by df0d387, @Kuree I can pull it in, but I didn't see the tests for slt, sle, smin. Are they on a separate branch? Or could you push them.

**Comment by Kuree** [comment]
I'll push them. I only have them on end-to-end tests. I will make unit tests.

**Comment by leonardt** [comment]
Okay thanks, probably easiest to push them to the smax branch

**Comment by Kuree** [comment]
Pushed. My mistake on `slt` and `sle`, I was using the wrong condition code. So far only `smax` and `smin` is not working.

Question though,  why `sle` and `slt` doesn't have signed set in `asm.py`?

**Comment by leonardt** [comment]
That's likely a bug in the `asm.py` definition, but I'm not sure what the spec is supposed to be

**Comment by rdaly525** [comment]
I do not think that SLE nor SLT needs the signed bit set. The flags should be appropriately set based off of the subtract. Possibly a bug in the flags.
