### ISSUE TITLE
Leverage the functional tests to do RTL tests

### ISSUE THREAD

**Issue by rdaly525** [StanfordAHA/lassen#72]
One major issue we have seen is that we are missing a lot of RTL unit tests in lassen. Due to the nature of Peak we should be able to parameterize the functional tests (test_pe.py) to also do RTL tests.

**Comment by rdaly525** [comment]
The agreed strategy was to add a parameter to each test in test_pe called 'pe' which can be set to be either the functional model from gen_pe(family) or a new function with the same interface that runs fault and the RTL. I think this can be accomplished with pytest fixtures. @Kuree said he could work on this.

One benefit of this is that we do not have to change any of the existing test code. We should also be able to do the same thing for SMT verification of the PE.

**Comment by phanrahan** [comment]
@leonardt and I discussed this last week. We agreed that we should be testing the rtl using the same tests that we are using to test the lassen simulation.

**Comment by rdaly525** [comment]
#73 was merged to master
