### ISSUE TITLE
Please update the Garnetflow requirements when you use non-released version of packages

### ISSUE THREAD

**Issue by Kuree** [StanfordAHA/lassen#88]
I will work on a solution that will block merge if the PR fails GarnetFlow.

**Comment by rdaly525** [comment]
@Kuree, Are you referring to the FP hwtype changes? I asked you to make the changes required for this.

**Comment by Kuree** [comment]
No I'm referring to the install requirements here: https://github.com/StanfordAHA/lassen/blob/master/.travis.yml#L30

**Comment by rdaly525** [comment]
Sorry, I am still confused. What is your expected flow?

My flow is:
create branch fp on hwtypes
create branch on lassen pointing to hwtypes:fp
merge lassen branch
merge hwtypes branch
New PR in lassen to point to hwtypes master.
delete hwtypes:fp branch

What is your proposed flow?

**Comment by rdaly525** [comment]
Pointing this branch to hwtypes FP is just a way to make sure master will always pass and will only be in temporarily.

I am open to other ideas.

**Comment by Kuree** [comment]
My expected flow is
- create branch fp on hwtypes
- create branch on lassen pointing to hwtypes:fp
- *make a branch in GarnetFlow reflects the changes and make sure it passes*
- merge lassen branch
- merge hwtypes branch
- New PR in lassen to point to hwtypes master.
- delete hwtypes:fp branch
- *adjust changes in GarnetFlow*

I thought the ultimate goal of this project is to make sure the end-to-end flow green. It's not important anymore?

**Comment by rdaly525** [comment]
Sure that is fine.

If you come up with a good way to block merge based off of downstream dependencies, I would request to not have it build the repo for normal travis builds (only for PRs)
