### ISSUE TITLE
FP add/mult not working

### ISSUE THREAD

**Issue by Kuree** [StanfordAHA/lassen#94]
See https://buildkite.com/stanford-aha/lassen/builds/1#f7512cd6-f12f-455e-980a-3f25eafa2a84

Just a side note:
From now on every push and PR in lassen will trigger buildkite build, which tests the floating point ops with `CW` files. If you want to debug, please use `kiwi` to test locally.

EDIT:
I will improve the `rtl_tester` to intelligently choose different simulator based on the environment it's in. `GarnetFlow` is already doing that.

**Comment by leonardt** [comment]
Fixed by https://github.com/StanfordAHA/lassen/pull/95
